### ISSUE TITLE
[TODO] bbox에 따라 crop (due date: ASAP)

### ISSUE THREAD

**Issue by 4923** [wJJin/burn-diagnosis-ai-challenge#2]
# Submit a feature request or bug report

## Development Environment (생략 가능)
- Operating system: MacOS

## Current Behavior
baseline에 reg, cls 코드 통합 및 inference 정상적으로 작동하는 것 확인 (@wJJin 확인 완)

## Expected Behavior
- [ ] bbox에 따라 image crop해서 넘겨주는 작업
- [ ] bbox에 맞추면 크기가 달라지는 이슈 있을 수 있음 : padding -> 256에 맞출 것 (cls)
- [ ] cls에서 이미지를 어떻게 불러올 것인지에 대한 고민 : 1차적으로 크롭된 이미지 저장
- [ ] (가능하다면) test loader를 변형하여 저장 없이 불러오도록 하는 방법 적용

- loader 변형에 대한 건 (@wJJin 조언)
  1. 학습을 위한 모델에서는 원래 정답으로 제공하는 json 의 bbox
  2. 추론모델 테스트할 시 crop한 내용을 사용 할 것
  3. test에 대한 loader 를 다시 선언 : json bb 를 불러오고 클래스를 하나 더 생성 

## Other Relevant Information
- 기준 파일 : https://github.com/wJJin/burn-diagnosis-ai-challenge/blob/main/submit_code/date_11_01.ipynb (f3e8425ecf1e14047c5cb6053b8f3a0a930a47ae)

**Comment by 4923** [comment]
섞일 것 같아 브랜치 사용할 예정
